### ISSUE TITLE
Mean and standard deviation of scaled error

### ISSUE THREAD

**Issue by liuyunwu** [BaratiLab/AugLiChem#56]
Dear authors,
    I'm reading your paper "Improving Molecular Contrastive Learning via Faulty Negative Mitigation and Decomposed Fragment Contrast "is the figure 2b on page 16 of the paper encountered scaled error, I don't know how to draw this graph according to the experimental data, I wonder if you could tell me in detail what tools you used and what formula you scaled the data according to?

I am eagerly looking forward to your reply. Thank you very much!
Best,
Yunwu

**Comment by CoopLo** [comment]
Hello Yunwu,

Please contact the corresponding author for that work (Prof. Barati Farimani: barati@cmu.edu) with questions about that paper

Sincerely,
Cooper
