### ISSUE TITLE
Installation on W10 with conda

### ISSUE THREAD

**Issue by agiani99** [BaratiLab/AugLiChem#59]
I have been trying to install AugLiChem on W10 following installation and surprisingly all went smooth.
Now two things:
1) pip install auglichem seems to exit clean but from `from auglichem.molecule import Compose, RandomAtomMask, RandomBondDelete, MotifRemoval, MotifRemoval` did not work properly for a torch problem (torch_geometric seems to cause problems)

Here the cell response

------------------------------------------------------------------------------------------------------------------------
`FileNotFoundError                         Traceback (most recent call last)
Cell In [2], line 1
----> 1 from auglichem.molecule import Compose, RandomAtomMask, RandomBondDelete, MotifRemoval
      2 from auglichem.molecule.data import MoleculeDatasetWrapper
      3 from auglichem.molecule.models import GCN, AttentiveFP, GINE, DeepGCN

File ~\anaconda3\envs\auglichem\lib\site-packages\auglichem\molecule\__init__.py:1
----> 1 from auglichem.molecule._transforms import RandomAtomMask, RandomBondDelete, MotifRemoval
      2 from auglichem.molecule._compositions import Compose, OneOf

File ~\anaconda3\envs\auglichem\lib\site-packages\auglichem\molecule\_transforms.py:15
     12 from rdkit.Chem.BRICS import BRICSDecompose
     14 import torch
---> 15 import torch_geometric
     16 from torch_geometric.data import Data as PyG_Data
     18 from auglichem.utils import ATOM_LIST, CHIRALITY_LIST, BOND_LIST, BONDDIR_LIST

File ~\anaconda3\envs\auglichem\lib\site-packages\torch_geometric\__init__.py:4
      1 from types import ModuleType
      2 from importlib import import_module
----> 4 import torch_geometric.data
      5 import torch_geometric.loader
      6 import torch_geometric.transforms

File ~\anaconda3\envs\auglichem\lib\site-packages\torch_geometric\data\__init__.py:1
----> 1 from .data import Data
      2 from .hetero_data import HeteroData
      3 from .temporal import TemporalData

File ~\anaconda3\envs\auglichem\lib\site-packages\torch_geometric\data\data.py:9
      7 import torch
      8 from torch import Tensor
----> 9 from torch_sparse import SparseTensor
     11 from torch_geometric.data.storage import (BaseStorage, EdgeStorage,
     12                                           GlobalStorage, NodeStorage)
     13 from torch_geometric.deprecation import deprecated

File ~\anaconda3\envs\auglichem\lib\site-packages\torch_sparse\__init__.py:19
     17 spec = cuda_spec or cpu_spec
     18 if spec is not None:
---> 19     torch.ops.load_library(spec.origin)
     20 else:  # pragma: no cover
     21     raise ImportError(f"Could not find module '{library}_cpu' in "
     22                       f"{osp.dirname(__file__)}")

File ~\anaconda3\envs\auglichem\lib\site-packages\torch\_ops.py:110, in _Ops.load_library(self, path)
    105 path = torch._utils_internal.resolve_library_path(path)
    106 with dl_open_guard():
    107     # Import the shared library into the process, thus running its
    108     # static (global) initialization code in order to register custom
    109     # operators with the JIT.
--> 110     ctypes.CDLL(path)
    111 self.loaded_libraries.add(path)

File ~\anaconda3\envs\auglichem\lib\ctypes\__init__.py:382, in CDLL.__init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    379 self._FuncPtr = _FuncPtr
    381 if handle is None:
--> 382     self._handle = _dlopen(self._name, mode)
    383 else:
    384     self._handle = handle

FileNotFoundError: Could not find module 'C:\Users\Andrea.zaliani\anaconda3\envs\auglichem\Lib\site-packages\torch_sparse\_convert_cuda.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

2) with git clone one does not receive ./data_downloads folder to run notebooks
Where one can find the csv needed?

Best and thanks
andrea

`

**Comment by CoopLo** [comment]
Closed due to inactivity.
