### ISSUE TITLE
IndexError: index out of range in self

### ISSUE THREAD

**Issue by divyavani01** [BaratiLab/AugLiChem#66]
while running the code for "FreeSolv" database i am facing this issue, can someone help me out with this 

IndexError                                Traceback (most recent call last)
/home/ubuntu/AugLiChem/examples/molecule_dataset.ipynb Cell 12 line 6
      2 for bn, data in tqdm(enumerate(train_loader)):
      4     optimizer.zero_grad()
----> 6     _, pred = model(data)
      8     # data -> GPU
      9     #_, pred = model(data.cuda())
     11     if(train_loader.dataset.task == "classification"):

File ~/anaconda3/envs/augli_113/lib/python3.8/site-packages/torch/nn/modules/module.py:1102, in Module._call_impl(self, *input, **kwargs)
   1098 # If we don't have any hooks, we want to skip the rest of the logic in
   1099 # this function, and just call forward.
   1100 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102     return forward_call(*input, **kwargs)
   1103 # Do not call functions when jit is used
   1104 full_backward_hooks, non_full_backward_hooks = [], []

File ~/AugLiChem/auglichem/molecule/models/gcn.py:159, in GCN.forward(self, data)
    156 h = self.x_embedding1(x[:,0]) + self.x_embedding2(x[:,1])
    158 for layer in range(self.num_layer):
--> 159     h = self.gnns[layer](h, edge_index, edge_attr)
    160     h = self.batch_norms[layer](h)
    161     h = F.dropout(F.relu(h), self.drop_ratio, training=self.training)
...
--> 127     return src.index_select(self.node_dim, index)
    128 elif isinstance(edge_index, SparseTensor):
    129     if dim == 1:

IndexError: index out of range in self

**Comment by CoopLo** [comment]
I did not encounter this issue when I ran it. I did notice that a lot of packages in my `auglichem` environment are older versions. Maybe that's the issue? Here is my environment, can you try fixing any version mismatches and seeing if the issue persists?


`name: auglichem
channels:
  - fastchan
  - conda-forge
  - omnia
dependencies:
  - appnope=0.1.2=py38h10201cd_2
  - argon2-cffi=21.1.0=py38hea4295b_1
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bleach=4.1.0=pyhd8ed1ab_0
  - boost=1.74.0=py38h3578e97_3
  - boost-cpp=1.74.0=h128b0ad_5
  - bzip2=1.0.8=h3422bc3_4
  - ca-certificates=2022.12.7=h4653dfc_0
  - cairo=1.16.0=hb99c34e_1009
  - celluloid=0.2.0=pyhd8ed1ab_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.14.6=py38hc67bbb8_2
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=0.29.24=py38h6f2b01f_1
  - debugpy=1.4.1=py38h6f2b01f_1
  - decorator=5.1.0=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=heb65262_1005
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.10.4=h17b34a0_1
  - future=0.18.2=py38h10201cd_4
  - gettext=0.19.8.1=h049c9fb_1008
  - greenlet=1.1.2=py38h6f2b01f_1
  - icu=69.1=hbdafb3b_0
  - importlib-metadata=4.8.1=py38h10201cd_1
  - ipykernel=6.4.2=py38h2cb4d76_0
  - ipython=7.29.0=py38h2cb4d76_1
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd8ed1ab_0
  - jbig=2.1=h3422bc3_2003
  - jedi=0.18.0=py38h10201cd_3
  - jinja2=3.0.2=pyhd8ed1ab_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9d=h27ca646_0
  - jsonschema=4.1.2=pyhd8ed1ab_0
  - jupyter=1.0.0=py38h10201cd_6
  - jupyter_client=7.0.6=pyhd8ed1ab_0
  - jupyter_console=6.4.0=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py38h10201cd_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.2=pyhd8ed1ab_0
  - keras=2.11.0=pyhd8ed1ab_0
  - kiwisolver=1.3.2=py38h1670459_1
  - lcms2=2.12=had6a04f_0
  - lerc=3.0=hbdafb3b_0
  - libblas=3.9.0=12_osxarm64_openblas
  - libcblas=3.9.0=12_osxarm64_openblas
  - libcxx=12.0.1=h168391b_0
  - libdeflate=1.8=h3422bc3_0
  - libffi=3.4.2=hbdafb3b_4
  - libgfortran=5.0.0.dev0=11_0_1_hf114ba7_23
  - libgfortran5=11.0.1.dev0=hf114ba7_23
  - libglib=2.70.0=h67e64d8_1
  - libiconv=1.16=h642e427_0
  - liblapack=3.9.0=12_osxarm64_openblas
  - libopenblas=0.3.18=openmp_h5dd58f0_0
  - libpng=1.6.37=hf7e6567_2
  - libprotobuf=3.18.1=hccf11d3_0
  - libsodium=1.0.18=h27ca646_1
  - libtiff=4.3.0=h74060c4_2
  - libwebp-base=1.2.1=h3422bc3_0
  - libxml2=2.9.12=hedbfbf4_1
  - libzlib=1.2.11=hee7b306_1013
  - llvm-openmp=12.0.1=hf3c4609_1
  - lz4-c=1.9.3=hbdafb3b_1
  - markupsafe=2.0.1=py38hea4295b_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py38hea4295b_1005
  - nbclient=0.5.4=pyhd8ed1ab_0
  - nbconvert=6.2.0=py38h10201cd_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h9aa5885_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - ninja=1.10.2=hc021e02_1
  - notebook=6.4.5=pyha770c72_0
  - numpy=1.21.3=py38hbf7bb01_1
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=h062765e_1
  - openssl=3.1.0=h03a7124_0
  - packaging=21.2=pyhd8ed1ab_1
  - pandas=1.3.4=py38h3777fb4_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.2=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre=8.45=hbdafb3b_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.3.2=py38h02acf36_0
  - pip=21.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=h27ca646_0
  - prometheus_client=0.12.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.21=pyha770c72_0
  - prompt_toolkit=3.0.21=hd8ed1ab_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycairo=1.20.1=py38h13f96a6_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyhd8ed1ab_1
  - pyrsistent=0.17.3=py38hea4295b_3
  - python=3.8.12=hd949e87_2_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=1.10.0=cpu_py38ha3d347f_0
  - pytorch-cpu=1.10.0=cpu_py38hd610c6a_0
  - pytz=2021.3=pyhd8ed1ab_0
  - pyzmq=22.3.0=py38h51b17a6_1
  - rdkit=2021.09.2=py38hbcbf861_0
  - readline=8.1=hedafd6a_0
  - reportlab=3.5.68=py38h1ca7581_0
  - scikit-learn=1.0.1=py38hfeda2c9_1
  - scipy=1.7.1=py38hd0c9ec0_0
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=58.4.0=py38h10201cd_1
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h156473d_2
  - sqlalchemy=1.4.26=py38hea4295b_0
  - sqlite=3.36.0=h72a2b83_2
  - statsmodels=0.13.5=py38hb39dbe9_2
  - terminado=0.12.1=py38h10201cd_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - threadpoolctl=3.0.0=pyh8a188c0_0
  - tk=8.6.11=he1e0b03_1
  - torchvision=0.10.1=py38h4ddca67_0_cpu
  - tornado=6.1=py38hea4295b_2
  - traitlets=5.1.1=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.0=pyhd8ed1ab_1
  - widgetsnbextension=3.5.2=py38h10201cd_0
  - xz=5.2.5=h642e427_1
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=hee7b306_1013
  - zstd=1.5.0=h861e0a7_0
  - pip:
    - ase==3.22.0
    - auglichem==0.1.0
    - cachetools==5.0.0
    - charset-normalizer==2.0.7
    - commonmark==0.9.1
    - contourpy==1.0.7
    - coverage==6.1.1
    - fonttools==4.39.3
    - google-auth==2.6.0
    - googledrivedownloader==0.4
    - idna==3.3
    - importlib-resources==5.12.0
    - iniconfig==1.1.1
    - isodate==0.6.0
    - markdown==3.3.6
    - matplotlib==3.7.1
    - meshio==5.3.4
    - monty==2021.8.17
    - mpmath==1.2.1
    - networkx==2.6.3
    - oauthlib==3.2.0
    - palettable==3.3.0
    - plotly==5.3.1
    - pluggy==1.0.0
    - protobuf==3.19.4
    - py==1.10.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pymatgen==2022.0.16
    - pytest==6.2.5
    - pytest-cov==3.0.0
    - pyyaml==6.0
    - rdflib==6.0.2
    - requests==2.26.0
    - requests-oauthlib==1.3.1
    - rich==12.5.1
    - rsa==4.8
    - ruamel-yaml==0.17.17
    - ruamel-yaml-clib==0.2.6
    - sklearn==0.0
    - spglib==1.16.1
    - sympy==1.9
    - tabulate==0.8.9
    - tenacity==8.0.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - toml==0.10.2
    - tomli==1.2.2
    - torch-geometric==2.0.2
    - torch-scatter==2.0.9
    - torch-sparse==0.6.12
    - tqdm==4.62.3
    - typing-extensions==4.3.0
    - uncertainties==3.1.6
    - urllib3==1.26.7
    - werkzeug==2.0.3
    - yacs==0.1.8
prefix: /Users/clo/miniforge3/envs/auglichem
`

**Comment by divyavani01** [comment]
changed the versions but still facing the same issue.

**Comment by divyavani01** [comment]
I've tried with these versions but still facing the same issue.

**Comment by CoopLo** [comment]
Is this error occurring in `gcn.py` or in the pytorch geometric file? It appears like the data may be of the wrong shape. Did you modify the example notebook in any way?

**Comment by divyavani01** [comment]
The code is working fine if any dataset is given to download but its giving this error if i give a dataset of my own and when tried to run the same example notebook its giving above error at the model training part in the provided notebook...i have changed the code in MoleculeDatasetWrapper(MoleculeDataset) class so i am passing smiles_data,task,labels to the code without downloading the dataset.

**Comment by divyavani01** [comment]
No changes are made to the actual code, I tried running the same with my own dataset and also with the default dataset you have specified. But nothing worked out and was giving the same error always.

**Comment by CoopLo** [comment]
I found the error was due to the motif removal augmentation. I have pushed updated code that runs everything for me. Can you try this:

First clone the AugLiChem repo. Inside the main directory:
`conda create auglichem python=3.9`
Install pytorch according to your machine's specifications [here](https://pytorch.org/get-started/locally/)
Install torch-geometric according to your machine's specifications [here](https://pytorch-geometric.readthedocs.io/en/latest/install/installation.html)
`pip install .` 

If you do not encounter any issues I will update the auglichem package through pypi
