### ISSUE TITLE
package issue

### ISSUE THREAD

**Issue by HanzTantiangco** [BaratiLab/AugLiChem#67]
I have installed the requried packages as instructed in the installation guidelines. However, when I execute the pip install auglichem command, I get the following error:

----------------------------------------------------------------------------
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.

      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

----------------------------------------------------------------------------

**Comment by HanzTantiangco** [comment]
> Were you able to fix the issue?

Hi, thank you for your response. The issue was fixed by changing sklearn into scikit-learn in the setup.py file. I am also getting the error "TypeError: Can't instantiate abstract class MoleculeDatasetWrapper with abstract methods get, len." in the example notebooks. I look forward to your updates.

**Comment by CoopLo** [comment]
I've updated the package. Installation like this now runs without error for me. First clone the AugLiChem repo. Inside the main directory:
`conda create auglichem python=3.9`
Install pytorch according to your machine's specifications [here](https://pytorch.org/get-started/locally/)
Install torch-geometric according to your machine's specifications [here](https://pytorch-geometric.readthedocs.io/en/latest/install/installation.html)
`pip install .` 

If you do not encounter any issues I will update the auglichem package through pypi
