### ISSUE TITLE
[Random Atom Mask] Question and potential issue.

### ISSUE THREAD

**Issue by vincrichard** [BaratiLab/AugLiChem#69]
Hello and thank you for your work on AugLiChem.

I would like to confirm my understanding of the random atom mask, and if it is correct, raise a concern about the implementation.

Random Atom Mask augmentation is defined in the paper by:

> In atom masking, a node `v_i` is randomly masked by replacing the node feature `a_i` with the mask vector `m`,
> which is a unique vector different from all the node features in the database

In the implementation, the mask part correspond to the following part:

https://github.com/BaratiLab/AugLiChem/blob/d122d36a69f7fc2e99f32aef26e065533abd3f09/auglichem/molecule/_transforms.py#L84-L85

Where `ATOM_LIST` is defined here:

https://github.com/BaratiLab/AugLiChem/blob/d122d36a69f7fc2e99f32aef26e065533abd3f09/auglichem/utils/_constants.py#L4

So for each masked atom, the tensor which will be attributed would be `torch.tensor([120, 0])`.

In your tests, you are also verifying the mask but instead of the feature dimension (which is 1), you are checking the batch node dimension. 

https://github.com/BaratiLab/AugLiChem/blob/d122d36a69f7fc2e99f32aef26e065533abd3f09/auglichem/test/test_molecule.py#L73

So here you are checking that all atom has been masked by looking at the first feature of each node of the graph. 

While this works, in your case because your nodes as far as I could tell only use two features:
https://github.com/BaratiLab/AugLiChem/blob/d122d36a69f7fc2e99f32aef26e065533abd3f09/auglichem/molecule/data/_molecule_dataset.py#L196-L199

If we are using a larger amount of features, the augmentation will crash with the following error:

```
RuntimeError: The expanded size of the tensor (45) must match the existing size (2) at non-singleton dimension 0.  Target sizes: [45].  Tensor sizes: [2]
```

Overall, from my understanding, there might be one error with the mask apply. Instead of `torch.tensor([120, 0])` it should be `torch.tensor([120, 120])` in your case to make all features mask with the same token, was that your intention or is there a reason why you wanted to apply `torch.tensor([120, 0])` ?

A second issue might come from generalization, in this repository the codes works with two features, but in order to have the augmentation work for larger number of features it should be generalized. The following code might do the trick and will replace all features with `120`, i.e. the variable `len(ATOM_LIST)`:

```python
 for atom_idx in mask_nodes: 
     aug_mol_graph.x[atom_idx,:] = torch.tensor([len(ATOM_LIST)]) 
```

I might have misunderstood your motivation and be awfully wrong. Please enlighten me if that the case.

**Comment by CoopLo** [comment]
In Atom Masking, we set the atom index to 120 to indicate mask, and remove chiral information. I don't believe we ever looked at using more features to describe an atom in the molecular case
